### ISSUE TITLE
Token not added to requests.

### ISSUE THREAD

**Issue by mkote** [mebjas/CSRF-Protector-PHP#107]
I am trying to integrate CSRFProtector into a SPA with JSON payloads for requests and responses. The json is generated by a Vue.js component and is consumed by a PHP backend.

However, since the payload sent to the SPA is purely JSON, the ob_handler method will never inject the csrfprotector.js since it looks for <HTML> tags, and the tokens are therefore never set properly in the request header. The result is that every POST request is blocked because there is no token attached in the requests.

I've tried to include the javascript directly in the index.html, but i can't seem to get it to work.

Any ideas for a solution to this? Thanks in advance!

**Comment by mebjas** [comment]
@mkote 
> However, since the payload sent to the SPA is purely JSON, the ob_handler method will never inject the csrfprotector.js since it looks for tags, and the tokens are therefore never set properly in the request header. The result is that every POST request is blocked because there is no token attached in the requests.

The JSON payload must be sent from some HTML content running on the browser to the server. It's this HTML content that should have the token. Please include the library on the php script that generates this HTML. It'll ensure that the request sent has the token attached to it.

> I've tried to include the javascript directly in the index.html, but i can't seem to get it to work.
>
> Any ideas for a solution to this? Thanks in advance!
First of all attaching the JS code is not enough, as the token is generated by the PHP backend and sent as cookie. Can you change the `index.html` to `index.php` and add following lines:
```php
<?php
include_once __DIR__ .'/<path to library>/csrfp/libs/csrf/csrfprotector.php';

//Initialise CSRFGuard library
csrfProtector::init();

?>
<HTML>
... remaining html code
</HTML>
````

After all these, Can you inspect the network call going with the JSON payload from browser to server? If the token with name `csrfp_token` is being attached or not.
