### ISSUE TITLE
Hi Mebjas,

### ISSUE THREAD

**Issue by Priyanka-SB** [mebjas/CSRF-Protector-PHP#114]
Hi Mebjas,
One of the php application which i am working on is csrf susceptible.I am trying to consume this master php library of yours. Can you please help me on this? Attached is the screenshot of the structure of my application.Where to add the php library? Do i have to create a folder csrf under www folder and add all the files which you have zipped?
I already have index.php in my application but i also see your library also has it? Do i have to do something on this?  
<img width="212" alt="PHPProject" src="https://user-images.githubusercontent.com/50325882/57224608-a2ddef80-7027-11e9-8764-292367134786.PNG">

_Originally posted by @Priyanka-SB in https://github.com/mebjas/CSRF-Protector-PHP/issues/100#issuecomment-489601087_

**Comment by Priyanka-SB** [comment]
After library is referenced in all required files how do we test it to be csrf safe?

**Comment by Priyanka-SB** [comment]
How do we test it to be csrf safe after library is referenced in all required files?

**Comment by mebjas** [comment]
One quick check would be to see when requests (of different type - POST) are sent if they have token attached in the request. And if they are getting invalidated and refreshed after each succesful validation.

If you want to do a full test w.r.t your application you may want to write some integration test - and since CSRF exists due to property of browser, you may want to use selinium or some UI based test framework to full test it

**Comment by mebjas** [comment]
As for the original question

> In general you can put it in library folder. You need to make sure the library is referenced in all required files. If you have some common file which is referenced by all - that’d be best place to have this.
>
> More details - https://github.com/mebjas/CSRF-Protector-PHP/wiki/How-to-use

**Comment by Priyanka-SB** [comment]
Hi Mebjas,
Does this library takes care of csrf for POST request only or GET request also?(GET request also should be handled to be csrf safe if i am not wrong)

**Comment by mebjas** [comment]
Yes GET requests are supported. This wiki has details on that - https://github.com/mebjas/CSRF-Protector-PHP/wiki/verifyGetFor-rules

**However**
CSRF attacks are impactful in request where some actions are taken. Example: Profile Update, Password Change, Posting comment etc. In general it's recommended any system change uses `POST` or `PUT` verb supported by HTTP. 

And in that sense I'd advice you to go for same. 

Get support in this library is it's salient feature but at the same time I wouldn't recommend it.

**Comment by Priyanka-SB** [comment]
Thank You Mebjas.
1) In PHP Application, we are submitting data through JSON AJAX request in javascript to WebAPI.
2)Save Button is in footer.html which is included in all php files. Can we use this PHP Library and Initialise CSRFGuard library in footer.html?
3)Save Button which is in footer.html will open a modal popup which in turn has a save button to save to a API.

**Comment by mebjas** [comment]
> 2)Save Button is in footer.html which is included in all php files. Can we use this PHP Library and Initialise CSRFGuard library in footer.html?
No you cannot include this library in an `html` file. It has to be processed by php process. Also, this library has to be included on top. CSRF Protector library has dependency on session which needs to be called before any data is returned by the server.

**Comment by mebjas** [comment]
You have to include this library in the beginning of php controllers.

**Comment by Priyanka-SB** [comment]
Thank You Mebjas.Below are few more questions
This library generates a random token and stores in Session and validates these token against the values of the GET or POST request. But, In our application, we do not have the POST action performed on the form ,instead Save button click  will call modal Save popup and this pop up has a Save button which will submit data to the API.Attached the files for better understanding

1st attachment shows a Save button on click of which the pop up to commit the changes occur and on Save confirmation actual data is submitted to API
<img width="474" alt="ImagetoshowSaveoperation" src="https://user-images.githubusercontent.com/50325882/59246634-87738f00-8c3a-11e9-896e-707274246d4c.PNG">

2nd attachment shows the php file of the above attachment in which the form doesnt have method=POST and then there is a Save button on click of which Save Modal pops up and footer.html is included in which the actual Save button to submit to API is available
<img width="631" alt="fileforcsrf" src="https://user-images.githubusercontent.com/50325882/59246646-8e9a9d00-8c3a-11e9-98a9-21ae140f4b97.PNG">

3rd attachment is footer.html file in which actual data saving operation to API happens.As mentioned earlier it is  through JSON AJAX request in javascript to WebAPI.
<img width="614" alt="footer html" src="https://user-images.githubusercontent.com/50325882/59246660-98bc9b80-8c3a-11e9-8953-336b14c52363.PNG">

Can I still add csrf library to my php file? Noting that the form is not being Posted?

**Comment by mebjas** [comment]
Yes, you'd need to add here as well. The library injects a Javascript code which creates an interceptor for all form submission be it normal form or AJAX. It ensures that just before the form submission - latest token is attached to the ongoing request.
