### ISSUE TITLE
Need a folder structure for CSRFProtector

### ISSUE THREAD

**Issue by AjithKumar-Raj** [mebjas/CSRF-Protector-PHP#115]
Help me here @mebjas Can you tell me project folder structure for CSRFProtector in https://github.com/twilio/OpenVBX?

**Comment by AjithKumar-Raj** [comment]
@mebjas What is the difference between [PHP library](https://github.com/mebjas/CSRF-Protector-PHP) and [Apache 2.x.x Module](https://github.com/mebjas/mod_csrfprotector)

**Comment by mebjas** [comment]
> @mebjas What is the difference between [PHP library](https://github.com/mebjas/CSRF-Protector-PHP) and [Apache 2.x.x Module](https://github.com/mebjas/mod_csrfprotector)
> 
> Is it required to implement two of this or anyone?

No they are two implementations of the same design. For a PHP application you need not use the apache module.

For the former question please check this: https://github.com/mebjas/CSRF-Protector-PHP/issues/114#issuecomment-495191431

**Comment by mebjas** [comment]
@AjithKumar-Raj Does this solve your question?

**Comment by mebjas** [comment]
> Help me here @mebjas Can you tell me project folder structure for CSRFProtector in https://github.com/twilio/OpenVBX?

Looking roughly at the code - you can include this library in `./index.php` (https://github.com/twilio/OpenVBX/blob/master/index.php) or in each controllers (https://github.com/twilio/OpenVBX/tree/master/OpenVBX/controllers)

**Comment by mebjas** [comment]
Marking as closed.
