### ISSUE TITLE
Error on form pages that submit to themselves - 403 Access Forbidden by CSRFProtector!

### ISSUE THREAD

**Issue by ShazVM** [mebjas/CSRF-Protector-PHP#118]
Hi mebas,

I think I have tried everything to get to the bottom of this issue, but I am still struggling to find an answer.

I am integrating CSRF Protector into my php app and have come across a problem on any pages that contain a form that when submitted reloads the page. In my example I have an index,php page that contains a search box form (that submits to search.php) and a 'submit a post' form that submits to the same page i.e index.php.

The search form works properly as it submits to a different page which has the library included. The 'submit a post form' when submitted to the index.php page returns with the 403 Access Forbidden by CSRFProtector! error.  This is also the case on my settings.php page which also submits to itself and reloads the page on submission.

I'm wondering if you could advise me on what might be the issue here?

Kind regards

Shaz

**Comment by ShazVM** [comment]
I managed to get to the bottom of the problem. The solution was to use the no js version of the library. I'm still not sure what the issue was, but its working now, so all's well that ends well I guess :-)

**Comment by davidh71** [comment]
I'm experiencing the same problem. @mebjas : Is the no js the proper solution to this problem?

**Comment by mebjas** [comment]
No, that may not be the best solution. Can you share more details about this?

**Comment by davidh71** [comment]
Hi @mebjas ,
In my situation I am using ajax to call the same url that I am on and I get a 403 response from the ajax call.  How will this attach itself to the ajax call ?  If you have any reference for using with ajax I can start there.

**Comment by davidh71** [comment]
Here's an example that illustrates this.
Can i get the token and insert it when i generate the ajax call in the html ?

```
<?php
include_once __DIR__ .'/csrfp/libs/csrf/csrfprotector.php';
//Initialise CSRFGuard library
csrfProtector::init();

if (isset($_POST['foo']) ) {
	echo "bar";
	exit;
} 

?> 
<html><head>
<script src="js/jquery-2.2.4.min.js"></script>
<script>
	function doit(){
		console.log('doit');
		$.ajax( {
			url: "test.php",
			type: "POST",
			dataType: "json",
			data: { "foo":$("#foo").val(),"bar":2 },
			complete: function(res){
				console.log("return ajax",res);
			}
		});
	}
</script>
</head>
<body>
	<input name='foo' id='foo'>
	<a href="#" onclick="doit()">doit</button>
</body>
<html>
```

**Comment by davidh71** [comment]
@mebjas - got it working by grabbing the session value that i set my config name to.   is using the last item in that array the proper thing?  Any problems with this approach??
```

<?php
include_once __DIR__ .'/csrfp/libs/csrf/csrfprotector.php';
//Initialise CSRFGuard library
csrfProtector::init();



$session = end( $_SESSION['csrfp'] );

if (isset($_POST['foo']) ) {
	echo "bar";
	exit;
} 

echo <<<EOD
<html><head>
<script src="js/jquery-2.2.4.min.js"></script>
<script>
	

	function doit(){
		console.log('doit');

		$.ajax( {
			url: "test.php",
			type: "POST",
			dataType: "json",
			data: { "foo":$("#foo").val(),"bar":2, csrfp:'$session' },
			complete: function(res){
				console.log("return ajax",res);
			}
		});
	}
	
</script>
</head>
<body>
	<input name='foo' id='foo'>
	<a href='#' onclick='doit()'>doit</a>
</body>
<html>
EOD;

?>
```

**Comment by mebjas** [comment]
@davidh71 your first code example seems to be working correctly for me, it's attaching the token correctly and sending the token and request is getting validated.

Can you check if the csrfprotector.js is included properly in your config.php? this javascript file is responsible for handling tokens in the client side. I do not recommend the approach you have shared as solution, its a hack and sort of what this library attempts to solve.

As next steps can you do following:
1. verify csrfprotector.js is included in your html
2. can you use latest version of this library `v.1.0.3`

let me know if it still doesn't work.

**Comment by davidh71** [comment]
thanks @mebjas 
Downloaded the latest and confirmed that the js is included... still not working.
chrome showing js loaded and the test.php ajax call failing on 403
![Screenshot from 2020-06-27 04-44-21](https://user-images.githubusercontent.com/2146176/85918497-4e9c5d00-b831-11ea-975c-02e8ca81e715.png)

**Comment by davidh71** [comment]
@mebjas I thought this might have to do with #51 and a jquery load problem, so i reworked the php script as below.
The call is still blocked.  I see the request header has the token in it in the post.  
Let me know if you have any suggestions.

```
<?php

include_once 'csrfp/libs/csrf/csrfprotector.php';
//Initialise CSRFGuard library
csrfProtector::init();

if (isset($_POST['foo']) ) {
	echo "bar";
	exit;
} 

?> 
<html><head>

<script>
	function doit(){
		console.log('doit');
		
		var xhr = new XMLHttpRequest();
		xhr.open('POST', 'test.php');
		xhr.setRequestHeader('Content-Type', 'application/json');
		xhr.onload = function() {
			if (xhr.status === 200) {
				var userInfo = JSON.parse(xhr.responseText);
			}
		};
		xhr.send(JSON.stringify({
			foo: 'John Smith',
			bar: 34
		}));
		
	}
</script>
</head>
<body>
	<a href="javascript:void(0)" onclick="doit()">doit</button>
</body>
<html>
```

**Comment by mebjas** [comment]
This is a bit off, can you share again the version of `PHP` and the OS?

Also I modified php part of your script a bit to get the whole flow working (It was not giving 403 without it either though).

```php
<?php
include_once 'csrfp/libs/csrf/csrfprotector.php';
//Initialise CSRFGuard library
csrfProtector::init();

$jsonInput = file_get_contents('php://input');
if ($jsonInput) {
  $input_data = json_decode($jsonInput, /* assoc= */ true);
  if ($input_data && array_key_exists('foo', $input_data) ) {
    header('Content-Type: application/json');
    echo json_encode(array(
      'status' => 'success',
      'bar' => $input_data['bar'],
    ));
    exit;
  }
}
?> 
```

**Comment by davidh71** [comment]
Thanks for your continued help.  Updated script with your suggestion and it still returns 403.  
It works locally, but not on the server described below.
Are there any ini settings this depends upon?

PHP Version 7.3.19
Apache 2.4.43
CentOS Linux
VERSION="7 (Core)"

**Comment by mebjas** [comment]
I'd recommend debugging the library script in this case. I am not sure under what condition should the same thing work for me and not for you. 

You can try putting editing https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/csrf/csrfprotector.php#L226 in your local setup to see why the authorization is failing. The logic there is not too complicated and you might be able to debug by using `var_dump()`

```php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
	// Set request type to POST
	self::$requestType = "POST";

	// Look for token in payload else from header
	$token = self::getTokenFromRequest();
	var_dump($token);
	var_dump($_SESSION[self::$config['CSRFP_TOKEN']]);
	var_dump(self::isValidToken($token));

	// Currently for same origin only
	if (!($token && isset($_SESSION[self::$config['CSRFP_TOKEN']])
		&& (self::isValidToken($token)))) {

		// Action in case of failed validation
		self::failedValidationAction();
	} else {
		self::refreshToken();    //refresh token for successful validation
	}
}
```

Ideally `self::isValidToken($token)` should be `true` here but I assume it's not in your case, you could debug that method too to see whats happening.

**Comment by davidh71** [comment]
Thanks, that helped point me in the right direction.
It seems that the headers are being stripped somewhere.  
I added a special condition to .htaccess file, but i'm not sure why they are being stripped in the first place! 
So It's working now!  thank you.

Final question - is there a way to disable logging in the config ?

**Comment by mebjas** [comment]
Glad it helped

> Final question - is there a way to disable logging in the config ?
you can pass a custom logger which doesn't do anything. Is there a reason not to log error cases?

Link to `LoggerInterface` - https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/csrf/LoggerInterface.php

you can do something like
```php
class NoOpLogger implements LoggerInterface {
  public function log($message, $context = array()) { /* No Op */}
}

$logger = new NoOpLogger();

csrfProtector::init(/* $length = */  null, /* $action = */  null, $logger);

```

**Comment by volkan64** [comment]
Hi,

how do you solve it?
I have the same problem. Locally its working but prod not. What did you add into the .htaccess? 

Thanks in advance.
