### ISSUE TITLE
Rename default header name to prevent being cut by web-servers

### ISSUE THREAD

**Issue by georgique** [mebjas/CSRF-Protector-PHP#120]
Although RFC doesn't prohibit it, using underscores in header names is not common. And for example Nginx by default considers such headers as invalid unless underscore_in_headers param is set to "on". 
I suggest to make default header name "CSRF-Token" so it looks more consistent with standard header names and doesn't cause troubles with web-servers.

**Comment by mebjas** [comment]
Sounds good to me. Would you be interested in sending a PR with fix?

**Comment by polishdeveloper** [comment]
Just highlighting that this is pretty important issue. Apache 2.4 also removes that header (http://httpd.apache.org/docs/trunk/env.html - see "Passing broken headers to CGI scripts" section)

**Comment by mebjas** [comment]
Thanks for calling this out - @georgique and thanks for the fix @polishdeveloper
