### ISSUE TITLE
Local sending to post error everytime

### ISSUE THREAD

**Issue by boionfire81** [mebjas/CSRF-Protector-PHP#129]
**Describe the bug**
I followed the setup and how to use wiki guides. Used in a login page on a localhost (running wamp). Everytime I click submit it sends me to the post error page.

**To Reproduce**
Using wamp  -> setup per the wiki guides -> create a form -> initialize per the wiki guide -> attempt to submit form

**Expected behavior**
To process the form

** Error logs (Optional) **
message":"OWASP CSRF PROTECTOR VALIDATION FAILURE" in csrfp/log

**Additional context**
 - PHP Version 7.3.12
 - Browser Chrome

**Comment by mebjas** [comment]
Need more information, by any chance is your code Open Source?

**Comment by boionfire81** [comment]
Do you mind if I contact you through your email on your profile? The code is from a pay to use engine. I don't mind sharing but I also don't want to post it in the open.

**Comment by mebjas** [comment]
Ok

**Comment by mebjas** [comment]
Closing this topic here.
