### ISSUE TITLE
Documentation - PHP Version

### ISSUE THREAD

**Issue by RobTables** [mebjas/CSRF-Protector-PHP#135]
I was not able to find a minimum required PHP version in the documentation. I apologize if I just missed it.

**Comment by mebjas** [comment]
Thanks for raising this - added information in wiki - https://github.com/mebjas/CSRF-Protector-PHP/wiki#min-php-version

Min version is version 5.4

**Comment by mebjas** [comment]
Added a badge in README as well - https://github.com/mebjas/CSRF-Protector-PHP

Thanks for calling out.
