### ISSUE TITLE
PHP Library Issues

### ISSUE THREAD

**Issue by abiusx** [mebjas/CSRF-Protector-PHP#15]
- [x] config file existence is checked, instead existence of config parameters should be checked (maybe file is there but is not filled out?)
- [x] one-liner ifs dont need blocks.
- [x] only string comparisons require 3 ===, all other comparisons typically need ==
- [ ] Its better to use an instance of class (not mandatory) instead of static. Maybe someone uses multiple protectors with different rules?
- [x] the code state is not very bright. Lots of nested ifs can be broken out into private functions and then called. (authorisePost? should be authorizePost)
- [ ] PHPDOC comments are in wrong format and incomplete

these all are improvements and are not necessary to release. If the code works, seems fine to me.

**Comment by mebjas** [comment]
1. Documentation moved to `NaturalDoc`
2. Currently only one instance of CSRFP per script hence static
