### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by abiusx** [mebjas/CSRF-Protector-PHP#16]
Add a few configuration examples that are tested and shown to work with Wordpress, Joomla and similar apps. This makes it much easier for users to adapt.

**Comment by mebjas** [comment]
Information on configuration file at:
https://github.com/mebjas/CSRF-Protector-PHP/wiki/Configurations
https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/config.sample.php
