### ISSUE TITLE
AJAX requests are denied when using FormData Objects

### ISSUE THREAD

**Issue by SautdeChat** [mebjas/CSRF-Protector-PHP#19]
When submitting FormData objects via ajax, the data forwarded becomes:
[object FormData]&{{tokenName}}={{tokenValue}}
The protector considers this a fail and throws a 403.
To remedy this I have changed new_send() to this:

	function new_send(data) {
		if (this.method.toLowerCase() === 'post') {

			if (data !== null && typeof data === 'object') {
				data.append(CSRFP.CSRFP_TOKEN, CSRFP._getAuthKey());
			} else {
				if (data !== "") {
					data += "&";
				} else {
					data = "";
				}
				data += CSRFP.CSRFP_TOKEN +"=" +CSRFP._getAuthKey();
			}
		}
		return this.old_send(data);
	}

I hope this is correct and helps others with the same issue.

**Comment by mebjas** [comment]
@SautdeChat: thanks for pointing this out!, would you want to fork and send a pull for this? or should I implement it!

**Comment by SautdeChat** [comment]
@mebjas: You are welcome. And done.
I sent one for each branch, not sure if that is right/necessary with git. But they are there.

**Comment by mebjas** [comment]
Corresponding changes made to js base script!
https://github.com/mebjas/CSRF-Protector-PHP/commit/9bda571d7bac211f805d81b4f4067df39366ea08
