### ISSUE TITLE
Tokens mismatched with Internet Explorer

### ISSUE THREAD

**Issue by mithilesh12** [mebjas/CSRF-Protector-PHP#28]
CSRF Protector is working with Firefox, Chrome but it is not working with Internet Explorer (IE). I tested with IE8, IE10, IE11.

I observed that csrf_token posted ($_POST) by browser is correct. But csrf_token of session stored on previous request has been changed automatically (without changing by refresh etc.). and that is why tokens have been mismatched.

I observed that time gap between two contiguous requests also matter. This token mis-matching comes earlier if time gap is lesser. What is solution? Please Help Me!

**Comment by mebjas** [comment]
Hi I tested the code again on IE 11 it worked fine. But I see the problem is little different here.
Theoretically with per request token there should be a problem with multiple simultaneous requests sent with small gap. This is because:
lets say **request1** was sent before **request2** and **request2** was sent before **request1** was responded to. In this case, the `request1` and `request2` will have same token in request header cookie but once `request1` has been processed the token at server side will refresh and validation for `request2` will fail. 

**Solution**
The solution for this could be storing multiple tokens on server side, now as soon as a token is sent from client all tokens set before this one will be cleared, hoping that requests are processed by server in FIFO manner.

Better ideas are welcome!!

**Comment by mebjas** [comment]
@mithilesh12 is the problem same as I think it is?

**Comment by mithilesh12** [comment]
I explored the problem toward your first response, i get the issue is the submitting a HTML form multiple times on single submit click in Internet Explorer. Can you suggest me that how to prevent the re-submitting a form in Internet Explorer in same request? I have used twitter bootstrap.

**Comment by mebjas** [comment]
well that can be done:
as soon as you click on submit button, attach an event listener on the button at that point that it disables action on that button
It'd look like:
```js
$("#BUTTON_ID").on('click', function()) {
    $(this).unbnd('click');
    $(this).on('click', function(e) {
        e.preventDefault();
        e.stopPropagation();
    })
}
```

#**BUT**
I think a server side implementation / modification of CSRF Protector will solve this problem as well. Give me a night time, I'll implement it.

**Comment by mithilesh12** [comment]
I hope so. Thank you.

**Comment by mebjas** [comment]
Try this: https://github.com/mebjas/CSRF-Protector-PHP/tree/simultaneous-tokens

**Comment by mebjas** [comment]
infact the changes were made to `libs/csrf/csrfprotector.php` only. So just changing this file in your test setup should do:  https://raw.githubusercontent.com/mebjas/CSRF-Protector-PHP/simultaneous-tokens/libs/csrf/csrfprotector.php

**Comment by mithilesh12** [comment]
Thank you!
Will I have to change the code used from the below link? 
https://gist.github.com/mebjas/332718be6cbf2a26f8a2

// CODE
var formObj = document.getElementById('form-loaded-via-ajax');
// ^^ Use any form of method to get the DOM object here

formObj.addEventListener("submit", function(event) {
    if (typeof event.target[CSRFP.CSRFP_TOKEN] === 'undefined') {
        event.target.appendChild(CSRFP._getInputElt());
    } else {
        //modify token to latest value
        event.target[CSRFP.CSRFP_TOKEN].value = CSRFP._getAuthKey();
    }
});

**Comment by mebjas** [comment]
No this will remain same, the code just picks latest token from cookies and
send it with a form submit request

----------------------------------------------------------------------------
Kind Regards,
Minhaz | My Projects <http://cistoner.org/projects> | M
<http://cistoner.org/minhaz/>y blog <http://blog.minhazav.me/>

**Comment by mithilesh12** [comment]
Thank you. Now it works for me on Internet Explorer, great work.

**Comment by mebjas** [comment]
Closing the issue!

**Comment by gyegan** [comment]
I'm having this issue with IE 11 but some of the links on this post aren't valid any more.  Could somebody let me know how to resolve it?

**Comment by mebjas** [comment]
@gyegan could you create a new issue for this ... I'll look into it asap.
