### ISSUE TITLE
Ajax submit not always sending correct token

### ISSUE THREAD

**Issue by iguanaman** [mebjas/CSRF-Protector-PHP#29]
Great library but I'm having an issue where ajax submits of a form are only working on alternate attempts.  For example;

1st submit: No csrfp token sent, fails
2nd submit: Csrfp token sent, works
3rd submit: Same csrfp token as previous submit sent, fails
4th submit: Different csftp token sent, works

```
$("#form-request").submit(function() {

	$.ajax({
		type: "POST",
		url: $(this).attr('action'),
		data: $(this).serialize(), 
		complete: function(data, status) {
			if(status === "success") {
				makeAlert("Request for landing page sent successfully.");
				updateRequests();
			} else {
				makeAlert("Failed to send request for landing page. Please check you have a landing page for that domain already.", true);
			}
		}
	 });

	return false; // avoid to execute the actual submit of the form.
});
```

**Comment by mebjas** [comment]
Use the modified model, https://github.com/mebjas/CSRF-Protector-PHP/tree/simultaneous-tokens. This should solve issue 3rd submit issue.

Now for the 1st submit, if the token is not being sent, it means the script hasn't loaded, which should not happen. I'll try your script for 1st submit issue, while you check and tell if this one solves 3rd submit issue.

**Comment by iguanaman** [comment]
If it helps, the hidden input gets dynamically created at the same time the first ajax submits.  So, the script seems to be loaded.  Perhaps adding the hidden input occurs after the data for the form is serialized.

**Comment by iguanaman** [comment]
Unfortunately the modified model didn't solve my issue.  The 3rd, 5th, 7th and all further odd number requests fail due to sending the same token as the previous even request (which worked).  

On a positive note I was able to fix the issue by adding the following code
```
$.ajaxSetup({
	beforeSend: function(jqXHR, settings) {
		settings.data = $("#form-request").serialize() + "&csrfp_token=" + $.cookie("csrfp_token");
	},
});
```

So just before the send I force add the value from the cookies.

This to me confirms what I suspected above, the token isn't being added to the ajax call via js.  So at first we get no token, and from then on; the previous token - as they are only being read during 
```
data: $(this).serialize(), 
```
And whatever code injects the hidden field runs after this.

**Comment by mebjas** [comment]
can you tell me methods to reproduce the bug, coz I tried it in my system and it seemed to work well.
I tried this type of code: https://gist.github.com/mebjas/fb1f258cc4ac360ca63d

Infact I faced the issue of two key value pair with same key `csrfp_token` being sent

**Comment by mebjas** [comment]
Closing until more information is gathered
