### ISSUE TITLE
TypeError: event.target.href is undefined

### ISSUE THREAD

**Issue by rsantellan** [mebjas/CSRF-Protector-PHP#31]
When I do a clic on a link the following error appears on the javascript console.
Is this a problem or just a warning.

Regards.

**Comment by mebjas** [comment]
this is strange, I'll check it!
Thanks for posting @rsantellan

**Comment by mebjas** [comment]
@rsantellan can you check against the latest code?

**Comment by rsantellan** [comment]
With the lastest code is not happening so I close this!
Thank you!!
