### ISSUE TITLE
Config should be outside of vendor folder in a composer installation

### ISSUE THREAD

**Issue by stephenlawrence** [mebjas/CSRF-Protector-PHP#34]
When I install composer libraries I do not include my /vendor folder in my version control system. For this CSRF library I needed to have the configuration located in my ROOT_FOLDER/config/ folder but this library is hard-coded to look for it inside the installation folder. 

Add the ability to have the config file located in ROOT_FOLDER at config/csrf_config.php.

**Comment by stephenlawrence** [comment]
PR #35 added.

**Comment by mebjas** [comment]
This was fixed and merged.
