### ISSUE TITLE
Uncaught ReferenceError: ActiveXObject is not defined

### ISSUE THREAD

**Issue by jamespsterling** [mebjas/CSRF-Protector-PHP#36]
Getting issues with the JS library. 

```
Uncaught ReferenceError: ActiveXObject is not definedcsrfprotector_init @ 
csrfprotector.js:270window.onload @ index.php?logout:149
```

**Comment by mebjas** [comment]
Can you post more information like `OS`, `Browser`, `versions` ?
Thanks!

**Comment by jamespsterling** [comment]
Chrome 47, WIndows 7, latest version from github

**Comment by mebjas** [comment]
Cool, I'll test and check this, earliest in the morning today.
Its 3:40AM in here & I have had no coffee :)

Thanks for posting.

**Comment by mebjas** [comment]
I could not reproduce the error, with latest version of library on `Chrome 47.0.2526.106`, `Windows 10`.
Can you give me more pointers on how to reproduce this error?

Also a screenshot of your console if possible :)

@jamespsterling

**Comment by mebjas** [comment]
Closing until more information is gathered
