### ISSUE TITLE
TypeError: event.target.href is undefined 

### ISSUE THREAD

**Issue by koltejas** [mebjas/CSRF-Protector-PHP#41]
I found this in [closed ](https://github.com/mebjas/CSRF-Protector-PHP/issues/31) issues. 
But now it is happening again using the latest code.
This happens on clicking any link
**TypeError: event.target.href is undefined**
**error on line: var urlDisect = event.target.href.split('#');**

Please look into it.

**Comment by mebjas** [comment]
@koltejas line no?

**Comment by koltejas** [comment]
it is here
	
csrfprotector.js (line 286, col 17)

**Comment by mebjas** [comment]
@koltejas I'm not sure if you are using the latest code, as during the bug fix this issue was resolved.
Look at this: https://github.com/mebjas/CSRF-Protector-PHP/blob/master/js/csrfprotector.js#L302

**Comment by mebjas** [comment]
Although it wasn't `released`
You'd have to clone the repo for latest bug free code

**Comment by koltejas** [comment]
a huge oops moment! Now i did a fork and downloaded the master zip. not sure how i ended up with older files the first time. 
I did not get any errors using the latest code. Code works nicely. Thanks for this library.
