### ISSUE TITLE
csrfp_token is false

### ISSUE THREAD

**Issue by moryekram** [mebjas/CSRF-Protector-PHP#43]
Hello.I use your library csrfp_token in post data is false but in cookie it has value.
please help me.

**Comment by mebjas** [comment]
@moryekram That is strange, can you tell the method to reproduce this bug?

**Comment by moryekram** [comment]
I found the problem.This is because I have two file: 1 - index.php and 2 - process.php.
All request go to process.php first and after that will be sent to their modules.
But because my web application is single page, my home page is index.php.
The path of index.php & process.php is different.
Now when I call csrfprotector_init() js func in index.php and call csrfProtector::init() in  process.php , document.cookie does not have csrfp_token.
All response is in json format in process.php , so I can't call csrfprotector_init() js func in process.php.
Where should I call these functions???
Please help me.Thanks for reply.

**Comment by moryekram** [comment]
I found the problem.This is because I have two file: 1 - index.php and 2 -
process.php.
All request go to process.php first and after that will be sent to their
modules.
But because my web application is single page, my home page is index.php.
The path of index.php & process.php is different.
Now when I call csrfprotector_init() js func in index.php and call
csrfProtector::init() in  process.php , document.cookie does not have
csrfp_token.
All response is in json format in process.php , so I can't call
csrfprotector_init() js func in process.php.
Where should I call these functions???
Please help me.Thanks for reply.

**Comment by mebjas** [comment]
OK the way I understand it, `index.php` serves the HTML output. And `process.php` is called via AJAX, such that it responds in `JSON` format.

So you have to call `csrfProtector::init()` in `index.php` as well, as this function is not only responsible for validation of incoming requests but also for creating tokens and sending it to clients.  Also, you do not need to manually include the js file or call `csrfprotector_init()` as the library deals with this automatically whenever the output is HTML. 

So the solution is:
1. Add `csrfProtector::init()` in index.php as well as process.php
2. Remove any manual call to csrfprotector_init() `js` if you have added.

**Comment by moryekram** [comment]
Thanks a lot.I test it.

**Comment by moryekram** [comment]
Hello again.Excuse me.I test your solution but because of my html and js code generate dynamically, when removing manual call to csrfprotector_init() js, the library does not generate any token and my generated js code error.So I shuld call it manually in the head of index.php.But now after login first POST request has token that is different from cookie token.

**Comment by moryekram** [comment]
![files](https://cloud.githubusercontent.com/assets/18113847/16792678/e17b8a8a-48df-11e6-85c3-68c5e80cbfcd.png)

**Comment by moryekram** [comment]
I uploaded my files.This is zip file that I renamed it to png to allow uploading

**Comment by mebjas** [comment]
I checked the code
you haven't included the library in `index.php` or `process.php`. Can you upload your project as a github repository and share the link? I'd be able to help better in that case.

**Comment by moryekram** [comment]
I Uploaded my fresh codes.Before using your library.
Because my project is for my company ans is commercial, I can't upload it as a github project.

**Comment by mebjas** [comment]
Where have you `included` this library? Can you point me to line of code in the source code you uploaded?

**Comment by moryekram** [comment]
I will send you index.php and process.php after using the library.

**Comment by moryekram** [comment]
![files1](https://cloud.githubusercontent.com/assets/18113847/16792962/9187e8b8-48e2-11e6-968f-78c724940249.png)

**Comment by moryekram** [comment]
In index.php on line 46 for js call and on line 55 for php call functions.
In process.php on line 20 just for php call.

**Comment by mebjas** [comment]
Ok here's what you need to do:

**`index.php`**
1) `csrfProtector::init()` initialises the process, so call it on line `34`. It should be like:
```php
include_once('../csrf/libs/csrf/csrfprotector.php');
csrfProtector::init();
 ``` 
And remove it from `line 55`

2)  You do not have to include the csrf js library manually, as done on `line 42`. The php library automatically adds the script to HTML output at appropriate location. However you need to configure the config file properly for this. Here: https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/config.sample.php#L20, change it with the absolute path of js code. For example: `http://localhost/yourproject/js/csrfprotector.js`

3) You do not have to call the `csrfprotector_init()` method in js as you have done in `line 45-47`. If you look at the js code, it's already done here: https://github.com/mebjas/CSRF-Protector-PHP/blob/master/js/csrfprotector.js#L333

**`process.php`**
4) `process.php` seems good, though you might not have to use it like
```php
if ($_REQUEST['action'] != "getHadith"){//} && $_REQUEST["action"] != "login") {
    csrfProtector::init();
}
```
if you set the configuration properly. Check this wiki for this: https://github.com/mebjas/CSRF-Protector-PHP/wiki/Configurations. However this is not necessary.

**Comment by moryekram** [comment]
Hello again and thanks for your reply.Now I can use it.
