### ISSUE TITLE
csrfp_token does not change

### ISSUE THREAD

**Issue by moryekram** [mebjas/CSRF-Protector-PHP#44]
Hello.Why csrfp_token does not change?It is fixed in all get & post request, although it generates new csrfp_token and csrfp_token array size in session gets larger.

**Comment by mebjas** [comment]
@moyekram
That's expected behavior. The model works on per request token to provide better protection against possible mitm attack. 
So to allow users to open multiple tabs all unused tokens are stored in session. The moment one is validated all prev tokens are removed.

**Comment by moryekram** [comment]
OK, but in my app all get & post request send same token.So always it uses the first token in session and all other tokens are useless.isn't it unsecure?

**Comment by moryekram** [comment]
OK.I could solve it by adding path to setcookie in csrfprotector.php.Thanks a lot.
