### ISSUE TITLE
Should I use one CSRF token for all forms in the same page?

### ISSUE THREAD

**Issue by petrospap** [mebjas/CSRF-Protector-PHP#45]
Hello,  
I have question, how many CSRF tokens must i generate if I have 10 forms in one page
should I use 1 token for all? Or is better to generate 10 different tokens of each form?

OR

Should I use just one token for entire website, regardless of how many forms / posts has this website?

OR 

Should I change tokens on every different page?

Just I don't know what is the best way!

**Comment by mebjas** [comment]
If there was an option, you should still generate one token. However the way it works is, it generates **ONE** token **AUTOMATICALLY** & send it to client as cookie (and only scripts running on that page can access them). Now js code running on the script will attach the token with any form that is submitted. And when the request goes to server the token is consumed and a new one is generated.

The crux is, only one of the HTML form can be submitted at once, so one token is enough (this follow per request token concept). Now if you have 10 ajax request in your page, every time the request sent by client is completed, the token in the cookie will change and JS will automatically pick up the latest token and attach it with the request (again per request token).

Here are references:
Detailed design doc: https://docs.google.com/document/d/1h9tNACzhwyG1a-N25ThnqYJeM13c3OvDM6WXO0dznwI/edit#heading=h.ugl3o463wpvg

Low level design doc: https://docs.google.com/document/d/1WVn0YyPpausfGjUqgEJNdUUq_rBIwdlKLCateasb6lk/edit

**Comment by petrospap** [comment]
Thank you, clear enough!
