### ISSUE TITLE
send token just in cookie

### ISSUE THREAD

**Issue by moryekram** [mebjas/CSRF-Protector-PHP#46]
Hello.Is it safe to send token just in cookie to server? So it is not append to request parameters and cookie can has httpOnly flag.

**Comment by mebjas** [comment]
Well that won't serve the purpose. The way CSRF works is some attacker would initiate a request to your website from some another site. And with every request cookies associated with the website are always sent.
So if cookies are your parameters for validation, it will always pass, and your website will be prone to CSRF Attacks.

**Comment by moryekram** [comment]
OK.That's right.Thanks
