### ISSUE TITLE
Store CSRF token in javascript var instead of cookie

### ISSUE THREAD

**Issue by moryekram** [mebjas/CSRF-Protector-PHP#50]
Hello.What's your idea about storing token in javascript variable instead of cookie?

**Comment by mebjas** [comment]
Remember that CSRFP works on a per request token basis.

Consider a scenario where you have two tabs open and both have same token in js variable. One sends a request and get validated. So the token is refreshed at backend and sent back as var to a page open on that tab. But the other tab still has old token so validation will fail if a request is sent from that tab now.

Cookie being a global variable for all tabs for a domain, it adapts to new values.

**Comment by moryekram** [comment]
Hello.And what about using localStorage .

**Comment by mebjas** [comment]
That would work but the question is why not cookie.

**Comment by moryekram** [comment]
No particular reason . Because we want to get a security certificate and that institute wants cookies be httponly.

**Comment by mebjas** [comment]
Oh OK. If your application is https only, you can apply this change
https://github.com/mebjas/CSRF-Protector-PHP/pull/48
