### ISSUE TITLE
False positive on POST

### ISSUE THREAD

**Issue by gnm67** [mebjas/CSRF-Protector-PHP#51]
I have an issue in that the token is not being validated on all forms.
The library is configured and I have confirmed it does work.
But on some pages (sample attached) it always gives the 403 error.

[test2.html.txt](https://github.com/mebjas/CSRF-Protector-PHP/files/463769/test2.html.txt)

**Comment by mebjas** [comment]
@gnm67 is this the actual source code or one sent to browser after output is modified by CSRFP?

**Comment by gnm67** [comment]
The source code attached is the output from the browser after it has been modified by CSRFP

Original code is PHP.
The module is called using a auto-pre-pend file.

PHP 5.6 / Apache 2.4 / Windows 7 & 2012 Server

**Comment by mebjas** [comment]
wait, are you using the release `v0.1.0` ? if so could you test with the clone of this repository if you are facing same issues?

**Comment by gnm67** [comment]
I think I downloaded it from 'master'

**Comment by mebjas** [comment]
From the output it looks like it's you are using older version, try downloading this https://github.com/mebjas/CSRF-Protector-PHP/archive/master.zip and test with this.

Reason: If you look at https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/csrf/csrfprotector.php#L409 you'll find that code snippet (from your output)
```html
<script type="text/javascript">
window.onload = function() {
	csrfprotector_init();
};
</script>
```
is no longer attached to HTML output also in [line 399](https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/csrf/csrfprotector.php#L399) some extra hidden input is added for the library to work, which isn't available in your output.

**Comment by mebjas** [comment]
@gnm67 did you try?

**Comment by gnm67** [comment]
Sorry I'm on holiday this week I will try when I get back in the office next week.

Thanks, Gavin
Sent via mobile


---- minhaz wrote ----


@gnm67<https://github.com/gnm67> did you try?

-

**Comment by gnm67** [comment]
I have downloaded the master and done some more testing.

the page that is giving problems is the the login page after a logout.

the logout uRL is for example
\home\logout.php
\index.php?logout
when they have been logged out the URL is as above and the login screen displayed again.
with a POST action to for example
\home\login.php
\index.php

In these instances the POST always fails with the 403 error
if the page is changed to
\home\login.php
\index.php
then the login works OK.

**Comment by mebjas** [comment]
@gnm67 I think I know what going wrong. So when you logout you do something like `session_destroy()` which destroys the session for user and they are logged out.
What you could do here is 
 - rather than destroying session entirely only `unset` the variable you are validating for session.
- In case you need to destroy the session, could you just backup the token and feed it back to session?

If it's ok with you could you point me to logout script? just to validate the theory?

Also, thanks for reporting the bug we didn't think of this scenario :D

**Comment by gnm67** [comment]
I have checked our code and on the logout we do a 
```
session_unset();
session_destroy();

```
as a workaround I have done this
```
	//session_unset();
	//@session_destroy();
	if (isset($_SESSION["CSRFP_TOKEN"])) $temp = $_SESSION["CSRFP_TOKEN"];
	@session_unset();
	@session_destroy();
	@session_start();
	if (isset($temp)) $_SESSION["CSRFP_TOKEN"] = $temp;
```

**Comment by mebjas** [comment]
and it worked?

**Comment by gnm67** [comment]
this worked, but is a bit clumsy.
Also now having problems with phpmyadmin.
I had hoped that doing it in a auto-pre-pend would make it easier and would then cover all sites on the server, but it is causing too many problems to handle at the moment.
I will have to forget it for now and try doing it again either server wide or per site when I have more time.

**Comment by mebjas** [comment]
I don't get it. One thing is session_destroy() is creating issues with PMA.
Ideally what you should try is change logout logic to `unset($_SESSION['id_or_something'])`

though this means you have to look for this as a authentication thingy for logged in user. But ideally that's how it's done. 

How do you check if a user is logged in or not using session?

**Comment by gnm67** [comment]
The  session_destroy() is working fine for the logout.

the problem I have with PhpMyAdmin is just by applying the module then PMA fails with 403 errors.

**Comment by mebjas** [comment]
What I don't get is why applying this to PMA on the first place, although it should play along but I haven't tested. It could be PMA's internal CSRF Protection doesn't plays with this one. 

And if this is about PMA logging out with `session_destroy()`, I think that makes sense if both of them are working in same domain.

**Comment by gnm67** [comment]
We have many sites on each server, I was applying the module to the server as a auto-pre-pend file so that it is applied to everything rather than having to edit each individual site which could lead to it being forgotten.
The logging out `session_destroy() ` doesn't affect PMA.

**Comment by mebjas** [comment]
Oh that way. Put a filter on path of the script, something like this pseudocode
```
if not ( __DIR__ contain PMA PATH ) csrfp::init()
```
as a workaround for now

**Comment by mebjas** [comment]
@gnm67 so where are we on this? workaround works?

**Comment by gnm67** [comment]
yes the workaround worked.


________________________________

**Comment by mebjas** [comment]
Closing with the [blog - article](http://blog.minhazav.xyz/2016/11/04/logging-out-and-then-logging-in-throws-403-error-with-csrf-protector-php-fix-workaround)
