### ISSUE TITLE
Incomplete Configuration File error although config.php has values

### ISSUE THREAD

**Issue by lewislacook** [mebjas/CSRF-Protector-PHP#53]
I am experiencing an Incomplete configuration file fatal error, though my jsUrl checks out (path is correct), jsFile checks out, I have values for all of what is required. 

Here is my config file (with some info redacted for security):

<?php  
/*\*                                                                                                                                    
- Configuration file for CSRF Protector  
- Necessary configurations are (library would throw exception otherwise)  
- ---- logDirectory  
- ---- failedAuthAction  
- ---- jsPath  
- ---- jsUrl  
- ---- tokenLength  
  _/  
  return array(  
      "CSRFP_TOKEN" => "vccsrfp",  
      "logDirectory" => "../log",  
      "failedAuthAction" => array(  
              "GET" => 0,  
              "POST" => 0),  
      "errorRedirectionPage" => "http://mydomain.com/index.php",  
      "customErrorMessage" => "Failed CSRF",  
      "jsPath" => "../js/csrfprotector.js",  
      "jsUrl" => "http://mydomain.com/classic/resources/vendors/owasp/csrf-protector-php/js/csrfprotector.js",  
      "tokenLength" => 10,  
      "disabledJavascriptMessage" => "This site attempts to protect users against <a href=\"https://www.owasp.org/index.php/Cross-Sit
  e_Request_Forgery_%28CSRF%29\">  
      Cross-Site Request Forgeries </a> attacks. In order to do so, you must have JavaScript enabled in your web browser otherwise th
  is site will fail to work correctly for you.  
       See details of your web browser for how to enable JavaScript.",  
       "verifyGetFor" => array("_://_/_")  
  );

**Comment by mebjas** [comment]
That is super strange the library looks for these values
```php
public static $requiredConfigurations  = array('logDirectory', 'failedAuthAction', 'jsPath', 'jsUrl', 'tokenLength');
```

To add to that I tested your config and it worked for me. Are you double sure you are using this config file?

**Comment by mebjas** [comment]
@lewislacook

**Comment by lewislacook** [comment]
I'll have to check on that. Since I'm using a nonstandard path for the
library that is a distinct possibility.

On Sep 27, 2016 4:00 PM, "minhaz" <notifications@github.com> wrote:

@lewislacook <https://github.com/lewislacook>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mebjas/CSRF-Protector-PHP/issues/53#issuecomment-249980626>,
or mute the thread

**Comment by mebjas** [comment]
ok let's see who's culprit. change the line 135-141 in /libs/csrf/csrfprotector.php to
```php
// Validate the config if everythings filled out
foreach (self::$requiredConfigurations as $value) {
	if (!isset(self::$config[$value]) || self::$config[$value] == '') {
		var_dump($value);
		throw new incompleteConfigurationException("OWASP CSRFProtector: Incomplete configuration file!");
		exit;
	}
}
```

essentiallly add the `var_dump`

**Comment by mebjas** [comment]
just so that you know, I have made above changes in code to show missing val. https://github.com/mebjas/CSRF-Protector-PHP/commit/aba031c7bad39a54184852367b10c5ceb9d68ab8

**Comment by lewislacook** [comment]
I'll have to check my server set up; I'm getting nothing at all from the var_dump.  All I get is in my error_log:
PHP Fatal error:  Uncaught incompleteConfigurationE
xception: OWASP CSRFProtector: Incomplete configuration file! in /opt/decisionlink/staging/ui/build/production/Decisionlink/classic/res
ources/vendors/owasp/csrf-protector-php/libs/csrf/csrfprotector.php:138\nStack trace:\n#0 /opt/decisionlink/staging/ui/build/production
/Decisionlink/app.php(10): csrfProtector::init()\n#1 {main}\n  thrown in /opt/decisionlink/staging/ui/build/production/Decisionlink/cla
ssic/resources/vendors/owasp/csrf-protector-php/libs/csrf/csrfprotector.php on line 138
                                                
PHP Fatal error:  Uncaught incompleteConfigurationEx
ception: OWASP CSRFProtector: Incomplete configuration file! in /opt/decisionlink/staging/ui/build/production/Decisionlink/classic/resources/vendors/owasp/csrf-protector-php/libs/csrf/csrfprotector.php:138\nStack trace:\n#0 /opt/decisionlink/staging/ui/build/production/
Decisionlink/app.php(10): csrfProtector::init()\n#1 {main}\n  thrown in /opt/decisionlink/staging/ui/build/production/Decisionlink/classic/resources/vendors/owasp/csrf-protector-php/libs/csrf/csrfprotector.php on line 138

**Comment by mebjas** [comment]
ok this is coming from error error log. rather than `var_dump` add the line
```php
error_log(sprintf("Value causing issue = %s", $value));
```

or replace `csrfprotector.php` with latest version: https://raw.githubusercontent.com/mebjas/CSRF-Protector-PHP/master/libs/csrf/csrfprotector.php

**Comment by mebjas** [comment]
@lewislacook any updates?

**Comment by mebjas** [comment]
@lewislacook I guess I'll close this one, due to lack of repro steps

**Comment by mebjas** [comment]
marking this as closed, due to lack of information
