### ISSUE TITLE
Add secure flag to cookie for HTTPS sites

### ISSUE THREAD

**Issue by mberkowski** [mebjas/CSRF-Protector-PHP#54]
While assisting with a site that has incorporated this project, I noticed that the CSRF cookie is set without the secure flag.  As a feature request, consider setting the secure flag in the [`setcookie()` call](https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/csrf/csrfprotector.php#L326) when the code can detect it is running under HTTPS (via `$_SERVER['HTTPS']` for example) or as a configurable option.

**Comment by mebjas** [comment]
Yeah that's good if the application is `https` only, which sadly isn't a generic case as of now. Check this thread https://github.com/mebjas/CSRF-Protector-PHP/pull/48, there was a PR for the same. You could use it though if the app is actually `https` only.

**Comment by mberkowski** [comment]
The tight coupling to port 443 is problematic in that PR. There is risk though for sites that aren't guaranteed https all the time, so perhaps a default-off configuration option instead.

**Comment by mebjas** [comment]
yeah it can be made configurable with `default off`.

**Comment by mebjas** [comment]
feel free to send a PR, with config value as something like `httpsOnly` let's say

**Comment by mebjas** [comment]
Implemented with https://github.com/mebjas/CSRF-Protector-PHP/commit/6f12262f406bb9a5ebf94f9a535944d5cc9fa29a
