### ISSUE TITLE
False negatives on requests containing AJAX call

### ISSUE THREAD

**Issue by jimmy-p123** [mebjas/CSRF-Protector-PHP#57]
If I have a function that looks like:

`function test_csrfp()
{
	// echo AJAX request
}`

and I send a request that contains a call to this function, the same token is sent in the headers for both requests, but the server is expecting a different token for the second request. Is there a way around this?

**Comment by mebjas** [comment]
`and I send a request that contains a call to this function` - I couldn't get this?

Also the library implements a token-stack method where tokens are kept on server a token created later is consumed. So this should theoretically not happen. However if you give me more information I'll try to reproduce this.

**Comment by jimmy-p123** [comment]
I was able to replicate the issue with jQuery 1.12 and an index.php that looks just like this:

`include_once 'csrf-protector/libs/csrf/csrfprotector.php';
csrfProtector::init();

function test_csrfp()
{
    echo '<script src="jquery-1.12.0.min.js"></script>';
    echo '<script>$.ajax({method: "POST", url:"index.php", data: {name: "csrfp_test"}});</script>';
}

function ajax()
{
    echo "Success";
}

if ($_POST)
    ajax();

else
    test_csrfp();
`

**Comment by mebjas** [comment]
If you look at the library code - you'll see it buffers output generated by php and attaches script only if it's `HTML` output. Check this - https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/csrf/csrfprotector.php#L383

And this js script that is added does all magic. So try changing your code to have `<html>` and `<body>` elements

**Comment by jimmy-p123** [comment]
I've changed the example I gave above to include HTML and BODY tags as you suggested. I see that csrfprotector.js is correctly being served now where it wasn't before, but the issue remains. The csrfp_token in the request header is the same for both the request to load the page and the AJAX request on the page. 

Here's my updated example:

```
include_once 'csrf-protector/libs/csrf/csrfprotector.php';
csrfProtector::init();

function test_csrfp()
{
	echo
		'<html>
			<body>
				<script src="jquery-1.12.0.min.js"></script>
				<script>
					$.ajax({
						method: "POST",
						url:"index.php",
						data: {
							name: "csrfp_test"
						}
					});
				</script>
			</body>
		</html>';
}

function ajax()
{
	echo
		"<html>
			<body>Success</body>
		</html>";
}

if ($_POST)
	ajax();

else
	test_csrfp();

```

**Comment by mebjas** [comment]
So loading the page is a simple GET request while ajax is POST here. `Token is not refreshed unless consumed` and by default `tokens are consumed for POST and not for GET until explicitly mentioned in config`

**Comment by jimmy-p123** [comment]
Okay, thanks for bearing with me so far. That is making sense now. 

So when I change the config.php to do:
`"verifyGetFor" => array('http://localhost/index.php*'")`

the initial get is failing when I load the page, but I need to verify both requests. I'm assuming it's failing because the user doesn't have a session at that point? Is what I'm trying to do even possible?

**Comment by mebjas** [comment]
yeah you don't set CSRF token for landing page. By convention you don't set CSRF token for GET requests, but let's say you have a API endpoint like `GET /action?queryparam=param` then you can whitelist them for CSRF validation using `verifygetfor`

But no for landing page, you need to make a request to get first token, which is done by landing page.

**Comment by jimmy-p123** [comment]
My site is actually littered with places where we have GET requests exactly like you described. I thought it would be easiest if I could just verify all GET requests instead of having to find and list every place.

Would it not be possible to just put something like

```
if ($_SESSION)
{
	include_once 'csrf-protector/libs/csrf/csrfprotector.php';
	csrfProtector::init();
}
```

at the top of index.php?

**Comment by mebjas** [comment]
No that wouldn't work. imagine if a user types url and open a web page in your site. There is no way token will automatically be attached in this case. Also Session could be set in this case. you should validate GET request only when it's making some config changes in system (writing to system) which is normally done using POST. GET request is supposed to serve content as per standards.

**Comment by jimmy-p123** [comment]
So is the include for the CSRF-Protector only intended to be put for specific code paths that contain POST requests? If my PHP file handles both GET and POST requests in different spots, can I not just put the include at the top of that file?

**Comment by mebjas** [comment]
no no it has support for GET request. But you cannot put CSRF Protection on landing page, there has to be one page that delivers the token

**Comment by jimmy-p123** [comment]
I think I have completely missed a crucial bit of information. Does the csrf-protector even have built-in functionality for POSTing tokens for requests made through Ajax, or do I have to manually append the tokens to each Ajax request?

**Comment by jimmy-p123** [comment]
Now, with an empty verifyGetFor array, the Ajax request in my example is still being rejected. authorizePost() is failing because $_POST doesn't contain the csrf token. Any idea why?

**Comment by jimmy-p123** [comment]
I was able to track down the reason, but I don't know how to work around it. The Ajax request is being fired before the DOM has finished loading, so csrfprotector_init() is being called after the request has started.

**Comment by mebjas** [comment]
That's strange. Can you open a new issue with this problem? I'll try to reproduce the bug with information you provide there.

As a quick workaround you could start your ajax calls here: https://github.com/mebjas/CSRF-Protector-PHP/blob/master/js/csrfprotector.js#L334 <- i do not recommend this at all though.

**Again, Open a new ticket with this issue please**
