### ISSUE TITLE
Echoed form missing token

### ISSUE THREAD

**Issue by jimmy-p123** [mebjas/CSRF-Protector-PHP#60]
I've encountered a problem on my site. The situation is as follows:

I have a button on a page. Pressing that button sends a request via AJAX to the server, and then the response is placed, using jQuery, into a div that's already on the page. That response contains a `<form>` element. When that new `<form>`  is submitted, it is being blocked. When examining the form submission request I do not see the token, and when inspecting the DOM prior to form submission, the csrf `<input>` elements aren't located within the form. 

I am able to reproduce using this sample php script:
```
<?php
    include_once 'csrf-protector/libs/csrf/csrfprotector.php';
    csrfProtector::init();

    function ajax()
    {
        echo
            "<html>
                <head>
                    <script src='jquery-1.12.0.min.js'></script>
                </head>
                <body>
                    <div id='form'></div>
                    <script>
                        $(document).ready(function() {
                            $.ajax({
                                method: 'POST',
                                url: 'test.php',
                                data: {
                                    csrfp_test: 'csrfp_test'
                                },
                                success: function(response)
                                {
                                    $('#form').html(response);
                                }
                            });
                        });
                    </script>
                </body>
            </html>";
    }

    function echo_form()
    {
        echo
            '<html>
                <body>
                    <form method="POST" action="test.php">
                        <input name="form" value="value"/>
                        <input type="submit"/>
                    </form>
                </body>
            </html>';
    }

    if ($_POST['csrfp_test'])
        echo_form();

    else if ($_POST['form'])
        echo "SUCCESS";

    else
        ajax();
```
Have I thoroughly communicated my problem, and are you aware of any workarounds? Thanks.

**Comment by mebjas** [comment]
Interesting find ... this would not work with current logic of attaching event listeners on forms when dom is loaded .
I guess two options are 
1. Statically rewriting forms with token on server side.
2. Monitor New dom element addition on client side and take action there

**Comment by mebjas** [comment]
I'll update with a patch asap. Thanks for pointing

**Comment by mebjas** [comment]
If you want a quick workaround, you could reference https://github.com/mebjas/CSRF-Protector-PHP/blob/nojs-support/libs/csrf/csrfprotector.php#L387 this line of code where we statically rewrite `<form>` in output to add tokens.

I was looking at DOMAdded events in JavaScript which are now deprecated. So may be an option to extend ob_handler to deal with forced addition of token even if `<html` is not there in output.

**Comment by mebjas** [comment]
@jimmy-p123 
Another quick workaround that although beats the purpose of this library, will work as a quick hotfix.
Change your `echo_form()` to this:
```php

    function echo_form()
    {
        echo
            '<html>
                <body>
                    <form method="POST" action="index2.php">
                        <input name="form" value="value"/>
                        <input type="submit"/>
                        <input type="hidden" name="' .csrfProtector::$config['CSRFP_TOKEN'] .'" value="' .$_SESSION[csrfProtector::$config['CSRFP_TOKEN']][0] .'">
                    </form>
                </body>
            </html>';
    }
```
leverage the public methods in library to get data from it.

**Comment by mebjas** [comment]
@jimmy-p123 should be fixed with https://github.com/mebjas/CSRF-Protector-PHP/commit/d9c8cea7dca2b11a3abd6863cffe2a1cc733db4d check and verify

**Comment by mebjas** [comment]
@jimmy-p123 marking this as closed, reopen if the issue still exists

**Comment by jimmy-p123** [comment]
Yep, looks like that fixed it. Thank you.
