### ISSUE TITLE
Install nojs version with composer

### ISSUE THREAD

**Issue by the94air** [mebjas/CSRF-Protector-PHP#61]
how to install your nojs version via composer?

**Comment by mebjas** [comment]
@the94air - yeah there is no way as of now, will check if we can have branch level installation in composer and come back to you.

**Comment by mebjas** [comment]
Check this out on how to do it - https://lornajane.net/posts/2014/use-a-github-branch-as-a-composer-dependency. Added information in readme as well - https://github.com/mebjas/CSRF-Protector-PHP/blob/nojs-support/readme.md

Also I have pushed some changes to nojs version to support autoload - https://github.com/mebjas/CSRF-Protector-PHP/commit/e67599a8bf4f2665ae05eb320f1add2a05bc7daf

**Comment by the94air** [comment]
Thanks you are awesome :smi

**Comment by mebjas** [comment]
Assuming the issue to be solved, @the94air closing the issue

Thanks!
