### ISSUE TITLE
No csrf token added on form submission via JavaScript

### ISSUE THREAD

**Issue by jarrodirwin** [mebjas/CSRF-Protector-PHP#62]
Hey,

I have installed this library and it works great for everything except forms that submit via JavaScript. This is due to the form submit events not firing when submitted via JavaScript - a known issue/problem in web development.

Simple E.G.
<input type="file" name="uploadfile" onchange="this.form.submit()" />

You could get around this by always adding the token field to the DOM for all forms (as well as adding the on submit listener). I have tested this and it works for normal content surfaced on page load however requires extra checks for dynamically loaded content E.G. forms loaded in via AJAX. You could maybe use the global AJAX dataFilter callback to parse all response data and inject the token field however not sure if this is even the right approach to fix the initial problems.

Would love to hear your thoughts on this.

Cheers,
Jarrod.

PS: Sorry I originally posted this in mod_csrfprotector but was meant to be on this project. I have now moved and added more information.

**Comment by mebjas** [comment]
@jarrodirwin - is this same as https://github.com/mebjas/CSRF-Protector-PHP/issues/60 ?

**Comment by jarrodirwin** [comment]
Hi Mebjas, thanks for getting back to me.

That issue is somewhat linked in that dynamically loaded ajax content doesn't get the submit listener added and thus also wouldn't get the input added to the DOM solution but that is a different problem. That is more a problem with the solution.

If you take dynamically loaded content out of the picture, just a standard form that is loaded on page load and has the submit listener attached correctly is still broken when that form is submitted via JavaScript. This is due to the way browsers process form submissions via JavaScript and the fact none of the submit handlers are fired. This is a known "issue" and is something JS frameworks like backbone.js etc work around themselves.

Ideally you would want to always add the CSRF token field whenever the DOM is altered regardless on if it was via initial page load or via an ajax call - taking into account only those new forms in the DOM etc. 

Another option could be to change the way the CSRF tokens are added on form submit by overriding at the window.prototype level - see http://briancrescimanno.com/form-submit-method-doesnt-fire-submit-event-workaround/ for inspiration. As mentioned in the line, the issue with that exact code is that IE doesn't surface the HTMLElement value so they are then looping through all form elements in the DOM and adding the submit callback - which would cause the same issues as those mentioned in #60...

Personally, I like the approach of intercepting at the submit level (like your currently trying to do) as that way you wouldn't have to worry about dynamically loaded content. You'd just need a way to get that to work in IE =P

**Comment by mebjas** [comment]
True, I'm considering to add some server level solution of modifying buffered output (if it has corresponding patters) rather than relying purely on JS. That's at least try to solve the problem linked with forms getting attached to DOM in runtime.

Now about JS triggered submission, I received another issue - https://github.com/mebjas/CSRF-Protector-PHP/issues/63, which I'll try to reproduce. If it's far reaching, we need to have a solution / workaround around that.

Thanks for posting, will try to repro asap. Feel free to share if you have any suggestions / solutions!

**Comment by jarrodirwin** [comment]
Not sure if you've seen this CSRF Protection Library but it might give some insight on an output buffered approach - https://www.phpclasses.org/package/8252-PHP-Prevent-CSRF-request-security-attacks.html

**Comment by mebjas** [comment]
@jarrodirwin - added code to intercept the form.submit() method and added a wrapper to attach a token before it's sent. https://github.com/mebjas/CSRF-Protector-PHP/commit/cdf167dc36468a1f6564510be792a2298e32bae3

Could you pull and verify?

**Comment by jarrodirwin** [comment]
@mebjas This looks pretty good except I found a small bug in line 192 of csrfprotector.js whereby your not passing the event into the callback function.

`-       document.querySelector('body').addEventListener('submit', function() {
+       document.querySelector('body').addEventListener('submit', function(event) {
`

I've tested on Chrome and FF but run Ubuntu so haven't tried IE/Edge.

**Comment by mebjas** [comment]
Yeah it's not always needed as callbacks run is a closure scope. But have added anyway!

Thanks! Closing this.
