### ISSUE TITLE
Form submission through onchange is missing token

### ISSUE THREAD

**Issue by jimmy-p123** [mebjas/CSRF-Protector-PHP#63]
Got one more issue for you.

When I have a `form`, and I attempt to submit it using an `onchange` listener on an `input` element within, the requests are missing the token. If I submit the exact same form using a submit input though, the request is fine. 

I'm able to reproduce using this simplified example. Submit the form by changing and then clicking out of the input field, and you should see the request blocked. Click the submit button though, and you should see the success message:

```
<?php
    include_once 'csrf-protector/libs/csrf/csrfprotector.php';
    csrfProtector::init();

    function test_csrfp()
    {
        echo
            '<html>
                <body>
                    <form method="post"  action="index.php">
                        <input name="input" value="test" onchange="form.submit();">
                        <input type="submit">
                    </form>
                </body>
            </html>';
    }

    function success()
    {
        echo
            "<html>
                <body>Success</body>
            </html>";
    }

    if ($_POST)
        success();

    else
        test_csrfp();

```

I can work around it by giving the submit button an ID and then changing the `onchange`  to `document.getElementById().click()`. 

It actually appears that any time you manually invoke `.submit` for any Javascript form variable it gets rejected.

**Comment by mebjas** [comment]
@jimmy-p123 Interesting! I'll test and try to reproduce.
Thanks!

**Comment by mebjas** [comment]
So, I tested this on my system (Windows 10, Chrome ) and seems to be working just fine. I put breakpoints to validate what is hit:
![capture](https://cloud.githubusercontent.com/assets/3007365/22861883/9970d764-f149-11e6-8086-784743ed4415.PNG)

And you can see the call back for `addEventListner` is hit. I'll check for other browsers

**Comment by mebjas** [comment]
@jimmy-p123 - was able to reproduce this. This was because the library was not intercepting the call to `HTMLFormElement.submit()`.

I have pushed the changes - https://github.com/mebjas/CSRF-Protector-PHP/commit/cdf167dc36468a1f6564510be792a2298e32bae3, could you pull and verify ?

**Comment by mebjas** [comment]
@jimmy-p123 marking this as closed, reopen if the issue still exists

**Comment by jimmy-p123** [comment]
Looks good. Thanks again.
