### ISSUE TITLE
Calling parent's log function when trying to override functionality: private access

### ISSUE THREAD

**Issue by jimmy-p123** [mebjas/CSRF-Protector-PHP#64]
I'm trying to [override the logging function](https://github.com/mebjas/CSRF-Protector-PHP/wiki/Overriding-logging-function) using Method 2. However, I want to retain the default functionality, and just do more on top of it. My extended class looks like: 

```
class CSRFP extends csrfprotector
{
    public static function logCSRFattack()
    {
        parent::logCSRFattack();

        /* Other stuff */
    }
}
```

but `logCSRFattack` has `private` access right now, and doing this isn't currently supported. Any chance you could change this function to have `protected` access?

**Comment by mebjas** [comment]
Nice suggestion. Implemented!

**Comment by mebjas** [comment]
Closing it!
@jimmy-p123 - however I'm curious to know what type of logging are you going for. Also it'd be amazing if you could put a write up of how you extended the library to use your own custom logging. Might be useful to other users.

**Comment by jimmy-p123** [comment]
Oh I'm not doing anything fancy. The way our site works, we have activity logs for each customer individually, which we record in an SQL database. We wanted to both keep a global log file of all blocked requests across our entire site and insert an entry into the affected customer's log when a block happens. We have a function called `insert_log_message` to handle the SQL insert, so my overridden `logCSRFattack` is literally just:

```
protected static function logCSRFattack()
{
	parent::logCSRFattack();

	$msg = "Blocked a cross site request attempt at {$_SERVER['REQUEST_URI']} from {$_SERVER['HTTP_REFERER']}";
	insert_log_message($msg);
}
```
