### ISSUE TITLE
Help with submitting form

### ISSUE THREAD

**Issue by coach-z** [mebjas/CSRF-Protector-PHP#69]
I'm new to this library and trying to implement it, but don't quite understand an issue I'm running into.  I have a hidden form that has always been submitted via an anchor tag with JS to submit the form.  This fails validation on the page I'm posting to... but if I simply change the submission to a submit button it works fine.  Before I try to convince my boss to change the appearance, is there something I'm missing?

**Comment by mebjas** [comment]
@coach-z you are using `preventDefault()` method to stop link click taking it's intended action right?

**Comment by coach-z** [comment]
Here's a snippet of what I have... 
`$('#makePaymentLink').click( function(e) {
                e.preventDefault();
                $('#frmOweAcctInfoMakePymt').submit();
            });`

`<a href="javascript:;" id="makePaymentLink"> Click Me</a>`

**Comment by mebjas** [comment]
I thought preventDefault() was preventing the library to do it's intended purpose, but it seem to be working for me: the exact scenario.

```html
<form action="./demo.php" method="post" id="_jssubmitform">
    <div>USERNAME: <input type="text" name="formOnClick" id="ajaxpost_input"></div>
</form>
<div><a href="javascript:;" id="_clicklink">click</a></div>
```

```js
$(document).ready(function() {
    $('#_clicklink').click( function(e) { e.preventDefault(); $('#_jssubmitform').submit(); });
})
```

Is there any diff from scenario I'm trying?

**Comment by coach-z** [comment]
I can try to test it later tonight... I punted and styled my button as a link with CSS and it's working.  I'm sure it's something on my end, but appreciate the assistance.

**Comment by mebjas** [comment]
Yeah, kindly close the issue, if it's not coming up . 👍
