### ISSUE TITLE
Submit form vis JS/JQuery

### ISSUE THREAD

**Issue by coach-z** [mebjas/CSRF-Protector-PHP#79]
I'm using the latest version and have an issue with a Chrome Extension causing validation to fail on JS/Jquery submit.  Below is a simple test I setup, with 3 submission types (Ajax, Submit Button and Button that submits the form with Jquery.  They work in all browsers except the form submitted with Jquery in Chrome when I have a LastPass extension enabled in the browser settings.  Not sure what I can do to resolve and thought I'd throw it out there.

Posting Script
`<?php
/**
 * Created by PhpStorm.
 * User: Ben
 * Date: 3/24/2017
 * Time: 9:21 AM
 */

session_start();

include_once __DIR__ .'/csrf-protector-php/libs/csrf/csrfprotector.php';

//Initialise CSRFGuard library
csrfProtector::init();

?>

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Untitled Document</title>
    <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
</head>

<body>
<form id="frmTest" name="frmTest" action="script.php" method="post">
    <input type="hidden" name="name" value="Ted" />
    <input type="hidden" name="location" value="Las Vegas" />
    <button type="submit">Click Me For Submit</button>
</form>
<button type="button" id="form">Click Me For Form</button>
<button type="button" id="ajax">Click Me For Ajax</button>
<p></p>
<script type="text/javascript">
    $(document).ready(function(){
        $("#ajax").click(function(){
            $.ajax({
                type: 'POST',
                url: 'script.php',
                data: { name: "John", location: "Boston" },
                success: function(data) {
                    alert(data);
                    $("p").text(data);
                }
            });
        });
        $("#form").click(function(){
            $("#frmTest").submit();
        });
    });
</script>
</body>
</html>`

Receiving Script
`<?php
/**
 * Created by PhpStorm.
 * User: Ben
 * Date: 3/24/2017
 * Time: 9:32 AM
 */

include_once __DIR__ .'/csrf-protector-php/libs/csrf/csrfprotector.php';

//Initialise CSRFGuard library
csrfProtector::init();

$name = $_POST['name'];
$location = $_POST['location'];

echo "You win ".$name." from ".$location;`

**Comment by mebjas** [comment]
@coach-z
In your example

```html
<title>Untitled Document</title> <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script> Click Me For Submit Click Me For Form Click Me For Ajax
```
There doesn't seem to be any `#ajax` or `#form` or `#frmTest` on which jQuery added event listener.

**Comment by coach-z** [comment]
It keeps cutting off my paste... I emailed the sample scripts.

**Comment by mebjas** [comment]
@coach-z are you still facing the issue? if yes can you post the code to gist.github.com and share link? email flow is very difficult

**Comment by mebjas** [comment]
Closing due to lack of response
