### ISSUE TITLE
Issue on multiple tab processing at same time

### ISSUE THREAD

**Issue by bupradeep** [mebjas/CSRF-Protector-PHP#81]
I have two tabs loading same page(with different form data) on browser. And submitting the form almost same time on both tabs(the recently generated token appended in both requests).

Here one tab, which process secondly gets 403 issue.

Is there any way to solve this?.

Note: It is not occurring all times. Rarely we notice this issue, while executing these kind of simultaneous process.

**Comment by mebjas** [comment]
@bupradeep well this issue was addressed in previous few releases. Can you tell more on way to reproduce this, specifics of form and request types.

**Comment by mebjas** [comment]
@bupradeep - quick followup here, more information is needed to address this issue. Otherwise I shall mark this as closed.

**Comment by mebjas** [comment]
Closing due to no response.

**Comment by comsuoncha** [comment]
i'm have the same issue, this cause by "Clear all older tokens assuming they have been consumed".
When open the second tab, the first tab will fail because old token has been remove
