### ISSUE TITLE
"Master Version" Doesn't Call JavaScript INIT

### ISSUE THREAD

**Issue by GLStephen** [mebjas/CSRF-Protector-PHP#82]
The version of the JS file linked as the 'master' file here:

https://github.com/mebjas/CSRF-Protector-PHP/wiki/How-to-use

Does not match that in js/csrfprotector.js

It is missing this:

window.addEventListener("DOMContentLoaded", function() {
	csrfprotector_init();
}, false);

Which makes the whole thing work.

**Comment by mebjas** [comment]
Yeah documentation got outdated with new releases. Updated the link to release page.

Thanks :)
