### ISSUE TITLE
Documentation not Clear on Interaction of CSRFP_TOKEN in Config and JavaScript

### ISSUE THREAD

**Issue by GLStephen** [mebjas/CSRF-Protector-PHP#83]
In hindsight it is perfectly clear, but at first install the documentation is not clear about the interplay of CSRFP_TOKEN here https://github.com/mebjas/CSRF-Protector-PHP/wiki/Configurations and at the top of the csrfprotector.js file.

A note to indicate that changing the config value requires a change in the JS file would be very helpful.

**Comment by mebjas** [comment]
@GLStephen that ain't needed. If you see here - https://github.com/mebjas/CSRF-Protector-PHP/blob/master/libs/csrf/csrfprotector.php#L422 the token name is put in HTML output as hidden input and it's retrieved by the js code here - https://github.com/mebjas/CSRF-Protector-PHP/blob/master/js/csrfprotector.js#L147

**Comment by mebjas** [comment]
@GLStephen did that answer the question? Can I mark this as resolved?
