### ISSUE TITLE
HTML truncated when activate csrfProtector

### ISSUE THREAD

**Issue by ar-anvd** [mebjas/CSRF-Protector-PHP#84]
Hello. I am experiencing a strange behaviour when activate csrfProtector.

When I see the view source of the document, I have the [html](http://i.imgur.com/wMqjMII.png) content simply truncated at some point.

The only workaround that I have found is just insert a ton of line breaks after the end of document </html> to have all the markdown rendered.

If I disable the csrfProtector, then everything works fine. Another interesting point is that I have this behaviour only in production server. Any idea?

**Comment by mebjas** [comment]
@ar-anvd this is weird. Can you give me more information to reproduce this? What was your environment?

**Comment by mebjas** [comment]
@ar-anvd a quick follow up here, to see how to fix the bug, I need steps to reproduce them.
If it's fixed, by configuration itself, I'll mark this as closed.

**Comment by mebjas** [comment]
Marking as closed, due to lack of information.
