### ISSUE TITLE
Cookie set lost on ajax(POST) call

### ISSUE THREAD

**Issue by tiger154** [mebjas/CSRF-Protector-PHP#86]
Hi @mebjas,

First of all, Thank you so much providing this cool library.

***1. Issue***
 - While I was testing it I had critical issue that after renew(isValidToken and refreshToken) cookie **setcookie** seems like didn't work at all. issuing new token was success but it didn't set new cookie.
  Because of that It was using old token only, so it increase tokens infinitely. 

** I didn't put **QcsrfProtector::init();** at the top of index.php, as my application has some middle-ware  structure(such as https://laravel.com/docs/5.4/middleware). I put init() in one of my starting middle-ware. 

***2. Solution***
 -  If we don't add a $path value to setcookie(), it defaults to "the current directory". This means that if you set the cookie from /web/DEV/Classes/SetCookie.php, the cookie gets set to /web/DEV/Classes/, and anything above that path won't see that cookie. So my suggestion is simple.
1) Add '/' path as default. it would look like below. or 2) We need to write down about it on document as possible bug issue to people then they could find and set $path information properly  
 
```
setcookie(self::$config['CSRFP_TOKEN'],
                    $token,
                    time() + self::$cookieExpiryTime,
                    '/',  // <-- this is one I changed 
                    '',
                    (array_key_exists('secureCookie', self::$config) ? (bool)self::$config['secureCookie'] : false));
```

**Comment by mebjas** [comment]
Hi @tiger154  - yeah it seems this issue was faced by other users as well. Check this issue: https://github.com/mebjas/CSRF-Protector-PHP/issues/87

I guess solution mentioned there would work here as well.

**Comment by mebjas** [comment]
Please check if this: https://github.com/mebjas/CSRF-Protector-PHP/pull/89 shall help.
@tiger154

**Comment by mebjas** [comment]
Marking as done.
