### ISSUE TITLE
Cookie path issue

### ISSUE THREAD

**Issue by peterdutton** [mebjas/CSRF-Protector-PHP#87]
Hi,

I have come across an issue where, in a page that is mostly updated via AJAX, the token expires on the 'main' page. This is because in my setup the ajax calls are made to scripts in a subfolder,
 e.g. `/ajax/ajaxScript.php` whereas the main page is served at the root, `/app.php`.

I propose to work around this in my installation by setting the 'path' parameter on setcookie (in the `refreshToken` method of `csrfprotector.php`) to be `'/'` rather than being blank. This will mean that csrfprotector now only issues one cookie per application, rather than multiple cookies for each subfolder in use.

My question is, should this behaviour be the default? Or is it undermining the security of the approach?

**Comment by mebjas** [comment]
Actually all the params of the `setcookie` method can be made configurable. We did the same for secure flag.

I'll send a Pull Request where this is taken care of, thanks for suggesting.

About security implications, I don't see any security implications here, it's just about how many applications are being run under same domain. It's purely developer choice.

**Comment by mebjas** [comment]
@peterdutton - please check this https://github.com/mebjas/CSRF-Protector-PHP/pull/89

**Comment by mebjas** [comment]
Marking as done.

**Comment by peterdutton** [comment]
Thanks for this @mebjas - much appreciated!
