### ISSUE TITLE
Delete .git folder from csrf-protector-php in composer 

### ISSUE THREAD

**Issue by elieobeid7** [mebjas/CSRF-Protector-PHP#93]
When installing this library using composer, you'll see inside the folder `csrf-protector-php`, a `.git`

Please remove `.git` folder, because if you're trying to commit the project, it will keep saying

> Changes not staged for commit:
> modified:   vendor/owasp/csrf-protector-php (modified content, untracked content) 

Here:

https://stackoverflow.com/a/5898123/1920003

Removing `.git` folder fixed my issue with git commit too

**Comment by mebjas** [comment]
Thanks for posting, will check and get back to you.

**Comment by elieobeid7** [comment]
deleting `.git` fixed the issue above but now if i do `composer update` I get

>   - Updating owasp/csrf-protector-php dev-master (88cfff1 => 638f411):     Updat                                                                                                               e failed (The .git directory is missing from D:\xampp\htdocs\web\diaspora\common                                                                                                               \vendor/owasp/csrf-protector-php, see https://getcomposer.org/commit-deps for mo                                                                                                               re information)
>     Would you like to try reinstalling the package instead [yes]?

It's the only composer i've ever seen that has `.git` folder included and it's the only package i've ever seen that relies on that folder for updates

**Comment by elieobeid7** [comment]
It seems that you deleted `.git` but you forgot to close the issue here. you could also delete `.gitignore` Thank you.
